### PR TITLE
Anonymously import the GCP auth provider to get the registration side effect.

### LINKED ISSUE #45: "Error: Get https://xxx.xxx.xxx.xxx/apis/apps/v1beta1: error executing access token command "/use/local/bin/gcloud ": exit status 2"
I'm using GKE, and as such my k8s credentials are like this:

```yaml
- name: foo
  user:
    auth-provider:
      config:
        access-token: REDACTED
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/bin/gcloud
        expiry: 2017-06-29T16:17:45Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

When I run `kubecfg update ...` I get the error `Error: Get https://xxx.xxx.xxx.xxx/apis/apps/v1beta1: error executing access token command "/usr/local/bin/gcloud ": exit status 2`.  If I run `kubectl get pods` it works, and subsequent `kubecfg update` commands work, until the token expires I guess.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #45 

Without this change, gcp auth was failing with `FATAL No Auth Provider found for name "gcp"`

### CODE REVIEW

**Comment by tomwilkie** [comment]
Failure is on Mac OS X, looks unrelated to this change.

File: cmd/root.go [hunk 1]
```diff
@@ -36,6 +36,7 @@ import (
 	"k8s.io/apimachinery/pkg/runtime/schema"
 	"k8s.io/client-go/discovery"
 	"k8s.io/client-go/dynamic"
+	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```
Comment (anguslees) [inline cmd/root.go]: Well spotted!

I've trivially extended your PR to include all auth plugins (gcp + oidc)

**Comment by tomwilkie** [comment]
Ah yes, good catch - I was trying to find the point they get register in kubectl, but navigating the codebase....
