### PR TITLE
Parse server GitVersion

### LINKED ISSUE #200: kubecfg should be more robust against bad server Major/Minor info
hi all

step 1， install the minikube and start
step 2.   download the release binary
step 3.   using the configuration under example and run kubecfg create, it'ok
step 4   trying to delete by running kubecfg delete, it failed like below

get error like below
`ERROR strconv.Atoi: parsing "": invalid syntax`

```
~/dev/kubecfg$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T17:03:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

```
 :~/dev/kubecfg$ ./kubecfg version
kubecfg version: v0.7.2
jsonnet version: v0.9.5
client-go version: v1.7.3-beta.0+$Format:%h$
(py36) yongweixing@ :~/dev/kubecfg$ ./kubecfg version
kubecfg version: v0.7.2
jsonnet version: v0.9.5
client-go version: v1.7.3-beta.0+$Format:%h$
```

```
 :~/dev/kubecfg$ minikube version
minikube version: v0.25.0
```

### PR DESCRIPTION
**Pull request by andresmgot**
Fixes #200 

In case that server version `Major` and `Minor` are not set or cannot be parsed use `GitVersion`. If all of the previous approaches fail use a default version. Using 1.8 as default version to match `client-go` current version.

### CODE REVIEW

File: utils/meta.go [hunk 1]
```diff
@@ -18,21 +19,39 @@ type ServerVersion struct {
...
+		return ServerVersion{}, err
 	}
+	return ret, nil
+}
 
+// ParseVersion parses version.Info into a ServerVersion struct
+func ParseVersion(v *version.Info) (ServerVersion, error) {
+	var ret ServerVersion
+	var err error
+	ret.Major, err = strconv.Atoi(v.Major)
```
Comment (arapulido) [inline utils/meta.go]: Shouldn't we check this error as well and return parseGitVersion if it is not nil? If not, the minor one below will overwrite this one.

Comment (andresmgot) [reply utils/meta.go]: true, missed the case in which `Major` is not correct and `Minor` is

File: utils/meta.go [hunk 2]
```diff
@@ -18,21 +19,44 @@ type ServerVersion struct {
 	Minor int
 }
 
+func parseGitVersion(gitVersion string) (ServerVersion, error) {
+	// Format v0.0.0(-master+$Format:%h$)
+	re := regexp.MustCompile("v([0-9])+.([0-9])+.[0-9]+-?.*")
```
Comment (anguslees) [inline utils/meta.go]: `MustCompile` panics if it doesn't compile - so is best used somewhere where it is _always_ invoked (and thus panics early enough that the developer _has_ to notice their error).

I suggest moving this up to a global:
```go
var gitVersionRe := regexp.MustCompile(...)

func parseGitVersion(...) {
  ...
}
```

Comment (anguslees) [inline utils/meta.go]: What's the trailing `-?` for?  Since `+` is a greedy operator by default, I think this regex is equivalent to just `...[0-9]+.*`

File: utils/meta.go [hunk 3]
```diff
@@ -18,21 +19,44 @@ type ServerVersion struct {
...
+	if len(parsedVersion) != 3 {
+		return ServerVersion{}, fmt.Errorf("Unable to parse git version %s", gitVersion)
+	}
+	var ret ServerVersion
+	var err error
+	ret.Major, err = strconv.Atoi(parsedVersion[1])
+	if err != nil {
+		return ServerVersion{}, err
+	}
+	ret.Minor, err = strconv.Atoi(parsedVersion[2])
```
Comment (anguslees) [inline utils/meta.go]: Can we still get a trailing + here, or does that only appear in the "real" `version.Minor` and not the gitVersion?  (I have no idea.  Perhaps look at a GKE version?)

File: utils/meta.go [hunk 4]
```diff
@@ -44,6 +68,11 @@ func FetchVersion(v discovery.ServerVersionInterface) (ret ServerVersion, err er
 	return ParseVersion(version)
 }
 
+// GetDefaultVersion returns a default server version (1.8)
```
Comment (anguslees) [inline utils/meta.go]: Add a comment here to make it clear that this fallback value is some time-sensitive guess and should not be assumed to stay the same forever.  Perhaps:
"This value will be updated periodically to match a current/popular version corresponding to the age of this code"

File: utils/meta.go (hunk 2 above)
Comment (andresmgot) [reply utils/meta.go]: it is, yes

File: utils/meta.go (hunk 3 above)
Comment (andresmgot) [reply utils/meta.go]: In theory it is not. The version should be in the format `v1.2.3` (the `+` suffix was a GKE is a way to specify that the git version was `v1.8.8` instead of `v1.8.0`)

File: utils/meta.go (hunk 4 above)
Comment (andresmgot) [reply utils/meta.go]: added
